import json
import os
import re

API_JSON_PATH = "../thoth-tarot-api/tarot_data.json"
WEB_JS_PATH = "public/src/js/cards.js"
INDEX_HTML_PATH = "public/index.html"

updates = {
    "adjustment": {
        "esoteric": {
            "hebrew": "ラメド (Lamed: 牛追い鞭)",
            "kabbalah": "ゲブラー(5) - ティファレト(6) [第22のパス]",
            "astrology": "天秤座",
            "alchemy": "真理の天秤による精緻な均衡と、カルマの正確な調整。",
            "iching": "恒（こう） - 雷風恒: 変わらぬ道、常に中心を保つバランス"
        },
        "symbols": [
            {
                "name": "剣と天秤を持つ女神（マアト）",
                "desc": "正義と宇宙の完全な均衡、厳格なカルマの法則。"
            },
            {
                "name": "つま先立ちのポーズ",
                "desc": "針の先のような一点の完全なバランス、動的平衡。"
            },
            {
                "name": "アルファとオメガの球体",
                "desc": "始まりと終わり、宇宙のすべての極性の統合。"
            },
            {
                "name": "ダチョウの羽",
                "desc": "マアト神の真理の羽。魂の重さを量る基準。"
            }
        ]
    },
    "hermit": {
        "esoteric": {
            "hebrew": "ヨド (Yod: 手)",
            "kabbalah": "ケセド(4) - ティファレト(6) [第20のパス]",
            "astrology": "乙女座",
            "alchemy": "隠された内なる光の抽出、孤絶した探求と精製。",
            "iching": "遯（とん） - 天山遯: 隠退、退くことで守る内なる叡智"
        },
        "symbols": [
            {
                "name": "ランプ（輝く太陽）",
                "desc": "ティファレトの光、暗闇を照らす内なる神性。"
            },
            {
                "name": "精子（精液の粒）とヨド",
                "desc": "創造の種子、生命の根源的な力の顕現。"
            },
            {
                "name": "3つの頭を持つ地獄の番犬（ケルベロス）",
                "desc": "道を塞ぐカルマの守護者、これを手懐ける力。"
            },
            {
                "name": "麦の穂とオルフェウスの卵",
                "desc": "豊穣、生命の神秘、宇宙の誕生。"
            }
        ]
    },
    "fortune": {
        "esoteric": {
            "hebrew": "カフ (Kaph: 掌)",
            "kabbalah": "ケセド(4) - ネツァク(7) [第21のパス]",
            "astrology": "木星",
            "alchemy": "絶え間ない変化の力、硫黄・水銀・塩の循環と流転。",
            "iching": "泰（たい） - 地天泰: 安泰と循環、天と地のエネルギーの交わり"
        },
        "symbols": [
            {
                "name": "10本スポークの車輪",
                "desc": "絶え間ない宇宙の回転、生命のサイクル。"
            },
            {
                "name": "スフィンクス（頂点）",
                "desc": "錬金術における硫黄。上昇するエネルギー、知性と意志。"
            },
            {
                "name": "ヘルマヌビス（上昇する神）",
                "desc": "錬金術における水銀。変化する流動的な知性、転生。"
            },
            {
                "name": "テュフォン（下降するワニ）",
                "desc": "錬金術における塩。下降するエネルギー、破壊と固着。"
            }
        ]
    },
    "lust": {
        "esoteric": {
            "hebrew": "テト (Teth: 蛇)",
            "kabbalah": "ケセド(4) - ゲブラー(5) [第19のパス]",
            "astrology": "獅子座",
            "alchemy": "バビロンの血、高次のエネルギーによる完全なトランスミューテーション（変容）。",
            "iching": "姤（こう） - 天風姤: 出会い、予期せぬ強烈な力の交わり"
        },
        "symbols": [
            {
                "name": "緋色の女（バビロン）",
                "desc": "神聖な霊的恍惚、宇宙の全エネルギーを乗りこなす力。"
            },
            {
                "name": "7つの頭を持つ獣",
                "desc": "宇宙の原始的な情熱と力。これらを抑圧せず統合する。"
            },
            {
                "name": "血で満たされた聖杯",
                "desc": "聖者たちの血、完全な自己犠牲と霊的な抽出。"
            },
            {
                "name": "蛇の形をした光（背景）",
                "desc": "宇宙に満ちる生命力（クンダリーニ）の完全な覚醒。"
            }
        ]
    }
}

def increment_version(match):
    prefix = match.group(1)
    current_version = int(match.group(2))
    return f"{prefix}{current_version + 1}"

def update_index_html():
    if not os.path.exists(INDEX_HTML_PATH):
        print(f"Warning: {INDEX_HTML_PATH} not found. Skipping cache buster update.")
        return

    with open(INDEX_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    # Automatically increment cards.js?v=XX and app.js?v=XX
    new_content = re.sub(r'(src/js/cards\.js\?v=)(\d+)', increment_version, content)
    new_content = re.sub(r'(src/js/app\.js\?v=)(\d+)', increment_version, new_content)

    if content != new_content:
        with open(INDEX_HTML_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated cache busters in index.html.")
    else:
        print("No cache buster updates were needed in index.html.")

def main():
    with open(API_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for card in data["major"]:
        if card["id"] in updates:
            card["esoteric"] = updates[card["id"]]["esoteric"]
            card["symbols"] = updates[card["id"]]["symbols"]

    with open(API_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    js_content = "// This file is automatically generated from local_tools/tarot_data.json\n"
    js_content += "// DO NOT EDIT MANUALLY\n\n"
    js_content += "const MAJOR_ARCANA = " + json.dumps(data["major"], ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const MINOR_ARCANA = " + json.dumps(data.get("minor", []), ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const ALL_CARDS = [...MAJOR_ARCANA, ...MINOR_ARCANA];\n"

    with open(WEB_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    # Cache buster automatic update
    update_index_html()

    print("Successfully updated the databases and cache busters.")

if __name__ == "__main__":
    main()
