import json
import os
import re

API_JSON_PATH = "../thoth-tarot-api/tarot_data.json"
WEB_JS_PATH = "public/src/js/cards.js"
INDEX_HTML_PATH = "public/index.html"

updates = {
    "cups_1": {
        "esoteric": {
            "sephira": "ケテル (Kether: 王冠)",
            "astrology": "水のエレメントの根源"
        },
        "symbols": [
            {"name": "聖杯（グラール）", "desc": "霊的な愛と受容の器。尽きることのない恩寵の源。"},
            {"name": "三つのリングを持つ光", "desc": "上位三セフィロト（ケテル・コクマー・ビナー）の霊的なエネルギーが聖杯に降り注ぐ。"}
        ]
    },
    "cups_2": {
        "esoteric": {
            "sephira": "コクマー (Chokmah: 知恵)",
            "astrology": "蟹座の金星"
        },
        "symbols": [
            {"name": "絡み合う2匹の魚（イルカ）", "desc": "蟹座と水の象徴。完全な調和と魂の深い結びつき。"},
            {"name": "溢れ出る水と2つの杯", "desc": "愛が枯渇することなく、互いを満たし合う完全な感情の交流。"}
        ]
    },
    "cups_3": {
        "esoteric": {
            "sephira": "ビナー (Binah: 理解)",
            "astrology": "蟹座の水星"
        },
        "symbols": [
            {"name": "ザクロの果実", "desc": "豊かさと生命のシンボル。ペルセポネの象徴。"},
            {"name": "黄金の3つの杯", "desc": "精神的な理解（ビナー）と感情が結びつき、豊かさが物質界へ溢れ出る。"}
        ]
    },
    "cups_4": {
        "esoteric": {
            "sephira": "ケセド (Chesed: 慈悲)",
            "astrology": "蟹座の月"
        },
        "symbols": [
            {"name": "黄金の装飾が施された杯", "desc": "感情的な豊かさの極致。しかし、水は流れず停滞し始めている。"},
            {"name": "安定した正方形の配置", "desc": "物質的な安定と感情的な満たされ方。同時に、変化のなさと倦怠感。"}
        ]
    },
    "cups_5": {
        "esoteric": {
            "sephira": "ゲブラー (Geburah: 峻厳)",
            "astrology": "蠍座の火星"
        },
        "symbols": [
            {"name": "ひび割れたガラスの杯", "desc": "感情的な喪失、崩壊、過去への執着による苦しみ。"},
            {"name": "枯れ果てた根と乾いた風", "desc": "生命力（水）が失われ、火星の攻撃性が感情の基盤を破壊した状態。"}
        ]
    },
    "cups_6": {
        "esoteric": {
            "sephira": "ティファレト (Tiphareth: 美)",
            "astrology": "蠍座の太陽"
        },
        "symbols": [
            {"name": "太陽の光を浴びる蓮の花", "desc": "感情の完全な再生と調和。ティファレト（美）の純粋な喜び。"},
            {"name": "6つの杯から溢れる水", "desc": "過去（5）の傷を癒やし、再び感情が自由に流れる健全な状態。"}
        ]
    },
    "cups_7": {
        "esoteric": {
            "sephira": "ネツァク (Netzach: 勝利/永遠)",
            "astrology": "蠍座の金星"
        },
        "symbols": [
            {"name": "毒々しい緑色のスライムとヒキガエル", "desc": "感情や欲望が過剰に腐敗し、不健全な幻想に溺れる状態。"},
            {"name": "割れた杯から漏れるヘドロ", "desc": "美（金星）が蠍座の深淵で堕落し、快楽主義が悪習に変わる。"}
        ]
    },
    "cups_8": {
        "esoteric": {
            "sephira": "ホド (Hod: 栄光)",
            "astrology": "魚座の土星"
        },
        "symbols": [
            {"name": "しおれた蓮と欠けた杯", "desc": "感情的なエネルギーの枯渇。土星の重圧によって水が淀む。"},
            {"name": "3つの空の杯と5つの満たされた杯", "desc": "まだ残っているものがあるにもかかわらず、気力を失い放棄する。"}
        ]
    },
    "cups_9": {
        "esoteric": {
            "sephira": "イエソド (Yesod: 基礎)",
            "astrology": "魚座の木星"
        },
        "symbols": [
            {"name": "完璧なシンメトリーに並ぶ9つの杯", "desc": "木星の恩恵による完全な感情的充足と深い幸福感。"},
            {"name": "豊かに咲き誇る蓮", "desc": "無意識（イエソド）の領域で感情が深く安定し、霊的な喜びに満ちている。"}
        ]
    },
    "cups_10": {
        "esoteric": {
            "sephira": "マルクト (Malkuth: 王国)",
            "astrology": "魚座の火星"
        },
        "symbols": [
            {"name": "巨大な生命の樹の形に並ぶ10の杯", "desc": "感情的経験の究極の到達点。すべてが満たされた最終形態。"},
            {"name": "傾いて水がこぼれる杯", "desc": "満たされすぎたため、これ以上の感情の入る余地がなく、次のサイクルへの崩壊（火星）を待つ。"}
        ]
    }
}

def increment_version(match):
    prefix = match.group(1)
    current_version = int(match.group(2))
    return f"{prefix}{current_version + 1}"

def update_index_html():
    if not os.path.exists(INDEX_HTML_PATH):
        print(f"Warning: {INDEX_HTML_PATH} not found. Skipping cache buster update.")
        return

    with open(INDEX_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = re.sub(r'(src/js/cards\.js\?v=)(\d+)', increment_version, content)
    new_content = re.sub(r'(src/js/app\.js\?v=)(\d+)', increment_version, new_content)

    if content != new_content:
        with open(INDEX_HTML_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated cache busters in index.html.")
    else:
        print("No cache buster updates were needed in index.html.")

def main():
    with open(API_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for card in data.get("minor", []):
        if card["id"] in updates:
            card["esoteric"] = updates[card["id"]]["esoteric"]
            card["symbols"] = updates[card["id"]]["symbols"]

    with open(API_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    js_content = "// This file is automatically generated from local_tools/tarot_data.json\n"
    js_content += "// DO NOT EDIT MANUALLY\n\n"
    js_content += "const MAJOR_ARCANA = " + json.dumps(data["major"], ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const MINOR_ARCANA = " + json.dumps(data.get("minor", []), ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const ALL_CARDS = [...MAJOR_ARCANA, ...MINOR_ARCANA];\n"

    with open(WEB_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    update_index_html()
    print("Successfully updated the Minor Arcana phase 2 databases and cache busters.")

if __name__ == "__main__":
    main()
