import json
import os
import re

API_JSON_PATH = "../thoth-tarot-api/tarot_data.json"
WEB_JS_PATH = "public/src/js/cards.js"
INDEX_HTML_PATH = "public/index.html"

updates = {
    "swords_1": {
        "esoteric": {
            "sephira": "ケテル (Kether: 王冠)",
            "astrology": "風のエレメントの根源"
        },
        "symbols": [
            {"name": "太陽と月が彫られた剣", "desc": "二元性（光と闇）を切り裂き、真実の核心に迫る純粋な知性の輝き。"},
            {"name": "王冠の貫通", "desc": "物質界の王冠を貫くことで、至高の真理（ケテル）へ直接アクセスする意志。"}
        ]
    },
    "swords_2": {
        "esoteric": {
            "sephira": "コクマー (Chokmah: 知恵)",
            "astrology": "天秤座の月"
        },
        "symbols": [
            {"name": "交差する2本の剣と青い薔薇", "desc": "対立する二つの力が互いに牽制し合い、一時的ながらも完璧な均衡（平和）を保つ状態。"},
            {"name": "月の静寂", "desc": "知性の活動が一時的に停止し、心が穏やかに休まるときの静かな緊張感。"}
        ]
    },
    "swords_3": {
        "esoteric": {
            "sephira": "ビナー (Binah: 理解)",
            "astrology": "天秤座の土星"
        },
        "symbols": [
            {"name": "薔薇を貫く3本の剣", "desc": "母なる理解（ビナー）の薔薇が、論理的思考の残酷な分析によって引き裂かれる苦痛。"},
            {"name": "嵐の背景", "desc": "精神的な重圧と土星の冷酷な現実認識による深い悲哀。"}
        ]
    },
    "swords_4": {
        "esoteric": {
            "sephira": "ケセド (Chesed: 慈悲)",
            "astrology": "天秤座の木星"
        },
        "symbols": [
            {"name": "中央に集まる4本の剣と薔薇", "desc": "争いから一歩引き、保護（ケセド）された空間で知的な妥協点を見出す。"},
            {"name": "緑色の背景", "desc": "木星の恩恵による一時的な回復と、傷を癒やすための静止状態。"}
        ]
    },
    "swords_5": {
        "esoteric": {
            "sephira": "ゲブラー (Geburah: 峻厳)",
            "astrology": "水瓶座の金星"
        },
        "symbols": [
            {"name": "いびつに曲がり欠けた剣", "desc": "ゲブラーの激しい力によって知性が破壊され、自己欺瞞と悪意が渦巻く状態。"},
            {"name": "逆五芒星", "desc": "精神が物質や低次の感情の奴隷となり、完全な敗北と屈辱を味わう。"}
        ]
    },
    "swords_6": {
        "esoteric": {
            "sephira": "ティファレト (Tiphareth: 美)",
            "astrology": "水瓶座の水星"
        },
        "symbols": [
            {"name": "六芒星の形に配置された剣と薔薇十字", "desc": "知性が完璧な美（ティファレト）のバランスに達し、客観的で冷徹な真理（科学）を確立する。"},
            {"name": "風車の的", "desc": "すべての思考が的の中央（核心）に向かって収束する、明晰で狂いのない論理。"}
        ]
    },
    "swords_7": {
        "esoteric": {
            "sephira": "ネツァク (Netzach: 勝利/永遠)",
            "astrology": "水瓶座の月"
        },
        "symbols": [
            {"name": "中心を外して突き刺さる剣", "desc": "努力の方向が定まらず、知性が感情（ネツァク）に邪魔されて空回りしている状態。"},
            {"name": "欠けた剣", "desc": "目標に到達する前に力が尽き、策略や妥協が最終的に無意味に終わること。"}
        ]
    },
    "swords_8": {
        "esoteric": {
            "sephira": "ホド (Hod: 栄光)",
            "astrology": "双子座の木星"
        },
        "symbols": [
            {"name": "邪魔し合う長さの違う剣", "desc": "過剰な思考の分析や外部からの細かな干渉により、本来の意図が完全に阻害される。"},
            {"name": "ランダムな幾何学模様", "desc": "思考が複雑に絡み合い、身動きが取れなくなる知的な自己破滅。"}
        ]
    },
    "swords_9": {
        "esoteric": {
            "sephira": "イエソド (Yesod: 基礎)",
            "astrology": "双子座の火星"
        },
        "symbols": [
            {"name": "血の滴る錆びた剣", "desc": "無意識（イエソド）の深層に潜む純粋な悪意、自虐的思考、激しい精神的苦痛。"},
            {"name": "鋸状の刃", "desc": "心を容赦なく切り刻む、救いのない自己批判と終わらない絶望のサイクル。"}
        ]
    },
    "swords_10": {
        "esoteric": {
            "sephira": "マルクト (Malkuth: 王国)",
            "astrology": "双子座の太陽"
        },
        "symbols": [
            {"name": "心臓を完全に破壊する10本の剣", "desc": "論理的な思考が極限まで行き着き、それ自体を崩壊させる完全な破滅。"},
            {"name": "太陽の狂気", "desc": "明確すぎる知性（太陽）が、逆にすべての幻想を焼き払い、物質的基盤（マルクト）を灰にする。"}
        ]
    }
}

def increment_version(match):
    prefix = match.group(1)
    current_version = int(match.group(2))
    return f"{prefix}{current_version + 1}"

def update_index_html():
    if not os.path.exists(INDEX_HTML_PATH):
        print(f"Warning: {INDEX_HTML_PATH} not found. Skipping cache buster update.")
        return

    with open(INDEX_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = re.sub(r'(src/js/cards\.js\?v=)(\d+)', increment_version, content)
    new_content = re.sub(r'(src/js/app\.js\?v=)(\d+)', increment_version, new_content)

    if content != new_content:
        with open(INDEX_HTML_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated cache busters in index.html.")
    else:
        print("No cache buster updates were needed in index.html.")

def main():
    with open(API_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for card in data.get("minor", []):
        if card["id"] in updates:
            card["esoteric"] = updates[card["id"]]["esoteric"]
            card["symbols"] = updates[card["id"]]["symbols"]

    with open(API_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    js_content = "// This file is automatically generated from local_tools/tarot_data.json\n"
    js_content += "// DO NOT EDIT MANUALLY\n\n"
    js_content += "const MAJOR_ARCANA = " + json.dumps(data["major"], ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const MINOR_ARCANA = " + json.dumps(data.get("minor", []), ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const ALL_CARDS = [...MAJOR_ARCANA, ...MINOR_ARCANA];\n"

    with open(WEB_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    update_index_html()
    print("Successfully updated the Minor Arcana phase 3 databases and cache busters.")

if __name__ == "__main__":
    main()
