import json
import os
import re

API_JSON_PATH = "../thoth-tarot-api/tarot_data.json"
WEB_JS_PATH = "public/src/js/cards.js"
INDEX_HTML_PATH = "public/index.html"

updates = {
    "hanged_man": {
        "esoteric": {
            "hebrew": "メム (Mem: 水)",
            "kabbalah": "ゲブラー(5) - ホド(8) [第23のパス]",
            "astrology": "水のエレメント",
            "alchemy": "溶解、固定された概念の破壊、大いなる海（ビナー）への回帰。",
            "iching": "困（こん） - 沢水困: 困難の中での試練と内面への沈潜"
        },
        "symbols": [
            {
                "name": "水の三角形",
                "desc": "下向きの三角形。水のエレメントと降下する恩寵。"
            },
            {
                "name": "十字架（アンク）",
                "desc": "永遠の生命。犠牲を通じて獲得される霊的な再生。"
            },
            {
                "name": "蛇（釘に打ち付けられた）",
                "desc": "死と再生、古いエゴの脱落。"
            },
            {
                "name": "逆さ吊りの姿勢",
                "desc": "視点の完全な逆転、物質的世界から霊的世界への価値観の転換。"
            }
        ]
    },
    "death": {
        "esoteric": {
            "hebrew": "ヌン (Nun: 魚)",
            "kabbalah": "ティファレト(6) - ネツァク(7) [第24のパス]",
            "astrology": "蠍座",
            "alchemy": "腐敗（Putrefactio）。古い形態が分解され、新しい形態の基盤となる究極の変容。",
            "iching": "剥（はく） - 山地剥: 剥がれ落ちる古い殻、破壊による浄化"
        },
        "symbols": [
            {
                "name": "鎌を持つ骸骨",
                "desc": "幻想を刈り取る宇宙の法則、避けられない変容のプロセス。"
            },
            {
                "name": "蠍と蛇と鷲",
                "desc": "蠍座の3つの段階。低次の欲求（蠍）から、知恵（蛇）、そして完全な解放（鷲）への進化。"
            },
            {
                "name": "泡と魚",
                "desc": "生命の源としての水。死の後に残る純粋な生命の種子。"
            },
            {
                "name": "踊る骸骨",
                "desc": "死は恐れるものではなく、宇宙の流転というダイナミックなダンスの一部である。"
            }
        ]
    },
    "art": {
        "esoteric": {
            "hebrew": "サメク (Samekh: 支柱)",
            "kabbalah": "ティファレト(6) - イエソド(9) [第25のパス]",
            "astrology": "射手座",
            "alchemy": "錬金術的結婚（Solve et Coagula）。対極の完全な統合と変容。大いなる作業の成就。",
            "iching": "鼎（てい） - 火風鼎: 錬金術の釜、三位一体の調和による新しい創造"
        },
        "symbols": [
            {
                "name": "両性具有の人物（アルテミス/ディアナ）",
                "desc": "VI. 恋人たちで分離していた二つが完全に融合した姿。"
            },
            {
                "name": "白い鷲と赤い獅子",
                "desc": "水銀と硫黄。対立する要素が互いの性質を交換し、完全に交じり合う。"
            },
            {
                "name": "大釜の中の水と火",
                "desc": "火によって水を燃やし、水によって火を消す、究極のパラドックスの成就。"
            },
            {
                "name": "虹（虹色のオーラ）",
                "desc": "錬金術の最終段階である「孔雀の尾」、神聖な霊的成就の光。"
            }
        ]
    },
    "devil": {
        "esoteric": {
            "hebrew": "アイン (Ayin: 目)",
            "kabbalah": "ティファレト(6) - ホド(8) [第26のパス]",
            "astrology": "山羊座",
            "alchemy": "物質への完全な受肉。粗大な物質の中に隠された純粋な霊的エネルギー（パンの力）。",
            "iching": "蹇（けん） - 水山蹇: 困難と停滞、物質界の限界に直面する"
        },
        "symbols": [
            {
                "name": "パン（森の神）",
                "desc": "生命の盲目的で純粋な創造エネルギー。男性性の極致。"
            },
            {
                "name": "巨大な雄ヤギと第三の目",
                "desc": "山羊座の象徴。物質世界を見透かす全能の目と、霊的洞察力。"
            },
            {
                "name": "男性器（男根）と睾丸",
                "desc": "宇宙の生命を生み出す無限の活力。"
            },
            {
                "name": "ガラスの管（宇宙の根源）",
                "desc": "下降する霊的エネルギーが物質と結びつく強烈な瞬間。"
            }
        ]
    }
}

def increment_version(match):
    prefix = match.group(1)
    current_version = int(match.group(2))
    return f"{prefix}{current_version + 1}"

def update_index_html():
    if not os.path.exists(INDEX_HTML_PATH):
        print(f"Warning: {INDEX_HTML_PATH} not found. Skipping cache buster update.")
        return

    with open(INDEX_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    # Automatically increment cards.js?v=XX and app.js?v=XX
    new_content = re.sub(r'(src/js/cards\.js\?v=)(\d+)', increment_version, content)
    new_content = re.sub(r'(src/js/app\.js\?v=)(\d+)', increment_version, new_content)

    if content != new_content:
        with open(INDEX_HTML_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated cache busters in index.html.")
    else:
        print("No cache buster updates were needed in index.html.")

def main():
    with open(API_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for card in data["major"]:
        if card["id"] in updates:
            card["esoteric"] = updates[card["id"]]["esoteric"]
            card["symbols"] = updates[card["id"]]["symbols"]

    with open(API_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    js_content = "// This file is automatically generated from local_tools/tarot_data.json\n"
    js_content += "// DO NOT EDIT MANUALLY\n\n"
    js_content += "const MAJOR_ARCANA = " + json.dumps(data["major"], ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const MINOR_ARCANA = " + json.dumps(data.get("minor", []), ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const ALL_CARDS = [...MAJOR_ARCANA, ...MINOR_ARCANA];\n"

    with open(WEB_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    # Cache buster automatic update
    update_index_html()

    print("Successfully updated the databases and cache busters.")

if __name__ == "__main__":
    main()
