import json
import os
import re

API_JSON_PATH = "../thoth-tarot-api/tarot_data.json"
WEB_JS_PATH = "public/src/js/cards.js"
INDEX_HTML_PATH = "public/index.html"

updates = {
    "wands_1": {
        "esoteric": {
            "sephira": "ケテル (Kether: 王冠)",
            "astrology": "火のエレメントの根源"
        },
        "symbols": [
            {"name": "炎をまとった棍棒", "desc": "純粋な霊的意志の最初の顕現。創造エネルギーの爆発。"},
            {"name": "落雷（10の光線）", "desc": "生命の樹（10のセフィロト）へ降り注ぐ純粋な火のエネルギー。"}
        ]
    },
    "wands_2": {
        "esoteric": {
            "sephira": "コクマー (Chokmah: 知恵)",
            "astrology": "牡羊座の火星"
        },
        "symbols": [
            {"name": "2本の交差するドルジェ（金剛杵）", "desc": "破壊と創造を司るチベットの法具。強大なエネルギーの制御。"},
            {"name": "炎とエネルギーの放射", "desc": "意志が明確な方向性を持ち、強力な支配力として発露する状態。"}
        ]
    },
    "wands_3": {
        "esoteric": {
            "sephira": "ビナー (Binah: 理解)",
            "astrology": "牡羊座の太陽"
        },
        "symbols": [
            {"name": "3本の蓮の花がついたワンド", "desc": "春の目覚め、意志（火）が母なる理解（水）と結びついて調和した誕生。"},
            {"name": "黄金の光", "desc": "太陽のエネルギーによる純粋で高潔な意図の輝き。"}
        ]
    },
    "wands_4": {
        "esoteric": {
            "sephira": "ケセド (Chesed: 慈悲)",
            "astrology": "牡羊座の金星"
        },
        "symbols": [
            {"name": "円形に配置された4本のワンド", "desc": "意志（火）が物質世界で最初の安定と法則を獲得した完全なる調和。"},
            {"name": "鳩と雄羊の頭飾りがついたワンド", "desc": "愛と平和（鳩）と、創造的エネルギー（雄羊）の結合。"}
        ]
    },
    "wands_5": {
        "esoteric": {
            "sephira": "ゲブラー (Geburah: 峻厳)",
            "astrology": "獅子座の土星"
        },
        "symbols": [
            {"name": "重くて太いクラブ（棍棒）", "desc": "重圧、制限、土星的な困難が火のエネルギー（獅子座）を抑圧・摩擦させる状態。"},
            {"name": "フェニックスのワンドと蓮のワンドの対立", "desc": "過去の遺物と新しい力の激しいぶつかり合い。"}
        ]
    },
    "wands_6": {
        "esoteric": {
            "sephira": "ティファレト (Tiphareth: 美)",
            "astrology": "獅子座の木星"
        },
        "symbols": [
            {"name": "均整の取れた6本のワンド", "desc": "闘争（5）を乗り越えた後の、完全なバランスと輝かしい勝利。"},
            {"name": "炎の十字と蓮の花", "desc": "太陽の中心でエネルギーが最も純粋かつ強力に調和している状態。"}
        ]
    },
    "wands_7": {
        "esoteric": {
            "sephira": "ネツァク (Netzach: 勝利/永遠)",
            "astrology": "獅子座の火星"
        },
        "symbols": [
            {"name": "バランスを崩しつつある6本と1本の太い棍棒", "desc": "圧倒的な不利な状況下での最後の決死の抵抗。"},
            {"name": "炎の揺らぎ", "desc": "安定が崩れつつあるが、火星の暴力的なエネルギーで辛うじて持ち堪えている。"}
        ]
    },
    "wands_8": {
        "esoteric": {
            "sephira": "ホド (Hod: 栄光)",
            "astrology": "射手座の水星"
        },
        "symbols": [
            {"name": "電光のように飛ぶ8本のワンド", "desc": "水星の知性とコミュニケーションの速度が、火のエネルギーに乗って一直線に進む。"},
            {"name": "虹色の背景", "desc": "思考とエネルギーが物質化する直前の、光のスペクトルのような純粋な速度。"}
        ]
    },
    "wands_9": {
        "esoteric": {
            "sephira": "イエソド (Yesod: 基礎)",
            "astrology": "射手座の月"
        },
        "symbols": [
            {"name": "太い柱のようなワンド", "desc": "内なる確固たる基盤、蓄積された無意識のエネルギーの強大な備え。"},
            {"name": "月と矢の象徴", "desc": "変化する状況（月）の中で、真っ直ぐに目的（矢）を見据える安定した力。"}
        ]
    },
    "wands_10": {
        "esoteric": {
            "sephira": "マルクト (Malkuth: 王国)",
            "astrology": "射手座の土星"
        },
        "symbols": [
            {"name": "鉄格子のように交差するワンド", "desc": "火のエネルギーが物質界の重圧（土星）によって完全に閉じ込められ、窒息している状態。"},
            {"name": "目を閉じたドルジェと燃え尽きた炎", "desc": "意志の力が盲目的になり、目的を見失ってただ重荷となっている。"}
        ]
    }
}

def increment_version(match):
    prefix = match.group(1)
    current_version = int(match.group(2))
    return f"{prefix}{current_version + 1}"

def update_index_html():
    if not os.path.exists(INDEX_HTML_PATH):
        print(f"Warning: {INDEX_HTML_PATH} not found. Skipping cache buster update.")
        return

    with open(INDEX_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = re.sub(r'(src/js/cards\.js\?v=)(\d+)', increment_version, content)
    new_content = re.sub(r'(src/js/app\.js\?v=)(\d+)', increment_version, new_content)

    if content != new_content:
        with open(INDEX_HTML_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated cache busters in index.html.")
    else:
        print("No cache buster updates were needed in index.html.")

def main():
    with open(API_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for card in data.get("minor", []):
        if card["id"] in updates:
            card["esoteric"] = updates[card["id"]]["esoteric"]
            card["symbols"] = updates[card["id"]]["symbols"]

    with open(API_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    js_content = "// This file is automatically generated from local_tools/tarot_data.json\n"
    js_content += "// DO NOT EDIT MANUALLY\n\n"
    js_content += "const MAJOR_ARCANA = " + json.dumps(data["major"], ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const MINOR_ARCANA = " + json.dumps(data.get("minor", []), ensure_ascii=False, indent=4) + ";\n\n"
    js_content += "const ALL_CARDS = [...MAJOR_ARCANA, ...MINOR_ARCANA];\n"

    with open(WEB_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    update_index_html()
    print("Successfully updated the Minor Arcana phase 1 databases and cache busters.")

if __name__ == "__main__":
    main()
